### ISSUE TITLE
Suggestion: update the Python code example within the Readme to show how arguments can be passed to PDFNumberer()

### ISSUE THREAD

**Issue by kburchfiel** [mikmart/pdfnumbering#2]
Thanks so much for creating this project! It's both easy to use and very helpful.

One suggestion would be to add some sample arguments to the PdfNumberer() initialization code within the Readme's Python example. This might be helpful to new users of pdfnumbering, as the formatting of these arguments differs somewhat from that of command line arguments. (Users can use the source code as a reference, but it could be helpful to show an example within the project's main page.)

Here's an example from my own application of pdfnumbering: (In this case, I'm adding small black page numbers to the bottom center of a letter-sized PDF file.)

```numberer = PdfNumberer(
    font_size=12, text_align = 'C', 
text_position = (0, 740), 
text_color = (0, 0, 0))```

(The equivalent arguments in a command line application of pdfnumbering would read:

`pdfnumbering --font-size 12 --text-align center --text-position 0 740 --text-color 000000 `)

**Comment by mikmart** [comment]
Thanks that's a good idea! And I'm glad to hear you've found this project helpful.
